### ISSUE TITLE
ly.fonts module?

### ISSUE THREAD

**Issue by uliska** [frescobaldi/python-ly#129]
I'm working on code to list, "install" and "uninstall" notation fonts, which will be used in the "Available Fonts" dialog in Frescobaldi and should also later be used in the New Score Wizard.

I could add this code as a `ly.fonts` module to `python-ly` in order to make it available outside of Frescobaldi too.

But I'm asking myself if this is appropriate because such a module would not operate on a LilyPond *document* but on an *installation*. One point where this becomes visible is that the objects couldn't work on a "lilypondinfo" object but would have to be passed a root directory manually.

From my perspective it is not much of a difference if I add this module to python-ly or to Frescobaldi itself, but I'd like to get some opinions.

**Comment by dliessi** [comment]
> But I'm asking myself if this is appropriate because such a module would not operate on a LilyPond document but on an installation.

Based on this, I think it would be more appropriate to add this to Frescobaldi.
