### ISSUE TITLE
eps-file should be epsfile in ly/words.py

### ISSUE THREAD

**Issue by mtarenskeen** [frescobaldi/python-ly#137]
https://github.com/frescobaldi/python-ly/blob/0d91ca2450ba01a8158f53ba05202af3e13bf78d/ly/words.py#L664

`eps-file` should be changed to `epsfile`

**Comment by PeterBjuhr** [comment]
Fixed by https://github.com/frescobaldi/python-ly/commit/1a4f23f3414e71e8db83c058cfb87ed4b414d456
