### ISSUE TITLE
Removing Python 2 support

### ISSUE THREAD

**Issue by jeanas** [frescobaldi/python-ly#154]
python-ly still declares Python 2.7 support in setup.py. However, Frescobaldi has long been using Python 3, Python 2.7 is very obsolete at this point, and I don't think anybody is testing it. Time to require Python 3, I guess?

**Comment by PeterBjuhr** [comment]
I'm not sure how many Python 3 features we actually use, but I agree - it would be good if we could take the step to require Python 3.
