### ISSUE TITLE
ly.pkginfo.name still in use

### ISSUE THREAD

**Issue by fedelibre** [frescobaldi/python-ly#167]
@jeanas In #155 you removed `ly.pkginfo.name`, but this is still used here:

```
$ git grep -n 'ly.pkginfo.name'
ly/musicxml/create_musicxml.py:58:        software.text = ly.pkginfo.name + " " + ly.pkginfo.version
```

This is causing [troubles to a user trying to export a lilypond file to XML](https://groups.google.com/g/frescobaldi/c/aO167zMjpgQ).

**Comment by jeanas** [comment]
Sorry about this. I've pushed the (trivial) fix as 233de7e253086c3eaad21c5b5223169832b36282.
